import { Language, LanguageCode } from './types';

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردু' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्' },
  { code: 'kok', name: 'Konkani', nativeName: 'कोङ्कणी' },
  { code: 'mni', name: 'Manipuri', nativeName: 'মণিপুরী' },
  { code: 'brx', name: 'Bodo', nativeName: 'बड़ो' },
  { code: 'ks', name: 'Kashmiri', nativeName: 'कश्मीरी' },
  { code: 'doi', name: 'Dogri', nativeName: 'डोगरी' },
  { code: 'mai', name: 'Maithili', nativeName: 'मैथिली' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली' },
  { code: 'sat', name: 'Santali', nativeName: 'संताली' },
];

export const TRANSLATIONS: Record<LanguageCode, any> = {
  en: {
    heroTitle: "Nirbhaya Sathi (Women Safety Platform)",
    heroSubtitle: "A complete, intelligent safety ecosystem connecting women and emergency responders across India.",
    emergencyBtn: "EMERGENCY SOS",
    aiAssistant: "AI Safety Assistant",
    safeRoute: "Safe Routes & Heatmap",
    community: "Community Network",
    reportIncident: "Report Incident",
    education: "Safety Education & Rights",
    familySafety: "Family Circle Mode",
    ruralSupport: "Rural & Village Support",
    citySmart: "Smart City Safety",
    quickActions: "Quick Safety Tools",
    sosAction: "Tap for immediate help",
    langName: "Language",
    chatPrompt: "How can I help you stay safe today?",
    fakeCall: "Fake Call",
    fakeCallDesc: "Simulate an incoming call to safely exit risky situations.",
    policeSiren: "Police Siren",
    policeSirenDesc: "Loud deterrent sound to alert nearby people.",
    voiceSos: "Voice SOS",
    voiceSosDesc: "Hands-free voice activated trigger (e.g. 'Help', 'Bachao').",
    safetyTimer: "Safety Timer",
    safetyTimerDesc: "Set a check-in countdown timer before walking.",
    policeFinder: "Police Finder",
    policeFinderDesc: "Find nearby police stations by name, district, or PIN code.",
    emergencyContacts: "SOS Contacts",
    emergencyContactsDesc: "Manage trusted contacts for instant SMS alert delivery.",
    liveTrip: "Live Trip Sharing",
    liveTripDesc: "Share real-time GPS movement link with loved ones.",
    safetyHeatmap: "Safety Heatmap",
    safetyHeatmapDesc: "View crowd-sourced safe and high-risk zones.",
    helplines: "Emergency Helplines",
    features: "Features & Tools",
    searchPolicePlaceholder: "Search by PS name, district, or PIN code (e.g. 712601, 712413)...",
    noPoliceFound: "No police stations found matching search criteria.",
    navigate: "Navigate",
    call: "Call",
    pinCode: "PIN Code",
    addContact: "ADD CONTACT",
    noContacts: "No contacts added yet.",
    startSharing: "START SHARING",
    stopSharing: "STOP SHARING",
    startTimer: "START TIMER",
    cancelTimer: "CANCEL TIMER",
    startListening: "START LISTENING",
    stopListening: "STOP LISTENING",
    joinNetwork: "Join Network",
    submitReport: "Submit Incident Report",
    adminPortal: "Admin Portal",
    policeController: "Police Station Controller",
    policeControllerDesc: "Live police emergency control room & distress dispatch monitor.",
    activeAlerts: "Active Distress Alerts",
    dispatchUnit: "Dispatch PCR Unit",
  },
  bn: {
    heroTitle: "নির্ভয়া সাথী (Nirbhoya Sathi)",
    heroSubtitle: "সাহসী নিরাপদ সঙ্গী - সারা ভারতের নারীদের সুরক্ষা ও সহায়তার ডিজিটাল প্ল্যাটফর্ম।",
    emergencyBtn: "জরুরি SOS সাহায্য",
    aiAssistant: "এআই সুরক্ষা সহকারী",
    safeRoute: "নিরাপদ রুট ও ম্যাপ",
    community: "কমিউনিটি নেটওয়ার্ক",
    reportIncident: "ঘটনা রিপোর্ট করুন",
    education: "সুরক্ষা শিক্ষা ও আইনি অধিকার",
    familySafety: "ফ্যামিলি সেফটি মোড",
    ruralSupport: "গ্রামীণ ও পঞ্চায়েত সহায়তা",
    citySmart: "স্মার্ট সিটি সেফটি",
    quickActions: "জরুরি সেফটি টুলস",
    sosAction: "তাত্ক্ষণিক সাহায্যের জন্য চাপুন",
    langName: "ভাষা",
    chatPrompt: "আজ আপনাকে কীভাবে সুরক্ষিত রাখতে সাহায্য করতে পারি?",
    fakeCall: "ফেক কল (Fake Call)",
    fakeCallDesc: "বিপদজনক পরিস্থিতি থেকে বের হতে নকল ফোনের সিমুলেশন।",
    policeSiren: "পুলিশ সাইরেন",
    policeSirenDesc: "আশেপাশের মানুষকে সতর্ক করতে উচ্চ শব্দের সাইরেন।",
    voiceSos: "ভয়েস SOS",
    voiceSosDesc: "কন্ঠস্বর চিনে স্বয়ংক্রিয় SOS ট্রিগার ('Help', 'বাঁচাও')।",
    safetyTimer: "সেফটি টাইমার",
    safetyTimerDesc: "যাত্রাপথে নির্ধারিত সময়ের মধ্যে চেকিং টাইমার।",
    policeFinder: "পুলিশ স্টেশন ডিরেক্টরি",
    policeFinderDesc: "নাম, জেলা বা পিন কোড দিয়ে কাছের থানা খুঁজুন।",
    emergencyContacts: "SOS ইমার্জেন্সি পরিচিতি",
    emergencyContactsDesc: "জরুরি মুহূর্তে আপনার পছন্দের মানুষদের SMS পাঠান।",
    liveTrip: "লাইভ ট্রিপ শেয়ারিং",
    liveTripDesc: "রিয়েল-টাইম জিপিএস লোকেশন প্রিয়জনদের সাথে শেয়ার করুন।",
    safetyHeatmap: "সেফটি হিটম্যাপ",
    safetyHeatmapDesc: "নিরাপদ ও ঝুঁকিপূর্ণ এলাকার মানচিত্র দেখুন।",
    helplines: "জরুরি হেল্পলাইন নম্বর",
    features: "সমস্ত ফিচার ও টুলস",
    searchPolicePlaceholder: "থানার নাম, জেলা বা পিন কোড দিয়ে খুঁজুন (যেমন 712601, 712413)...",
    noPoliceFound: "এই পিন কোড বা নামে কোনো পুলিশ স্টেশন পাওয়া যায়নি।",
    navigate: "ম্যাপে দেখুন",
    call: "কল করুন",
    pinCode: "পিন কোড",
    addContact: "যোগাযোগ যোগ করুন",
    noContacts: "এখনো কোনো নম্বর যোগ করা হয়নি।",
    startSharing: "শেয়ারিং চালু করুন",
    stopSharing: "শেয়ারিং বন্ধ করুন",
    startTimer: "টাইমার চালু করুন",
    cancelTimer: "টাইমার বাতিল করুন",
    startListening: "ভয়েস শোনা শুরু করুন",
    stopListening: "ভয়েস বন্ধ করুন",
    joinNetwork: "নেটওয়ার্কে যুক্ত হন",
    submitReport: "রিপোর্ট জমা দিন",
    adminPortal: "অ্যাডমিন পোর্টাল",
    policeController: "থানা কন্ট্রোল রুম (Police Controller)",
    policeControllerDesc: "লাইভ পুলিশ কন্ট্রোল রুম ও জরুরি ডিসপ্যাচ মনিটর।",
    activeAlerts: "সক্রিয় জরুরি অ্যালার্ট",
    dispatchUnit: "PCR ভ্যান পাঠান",
  },
  hi: {
    heroTitle: "निर्भया साथी (Nirbhoya Sathi)",
    heroSubtitle: "साहसी सुरक्षित साथी - पूरे भारत में महिलाओं की सुरक्षा का संपूर्ण डिजिटल तंत्र।",
    emergencyBtn: "आपातकालीन SOS",
    aiAssistant: "AI सुरक्षा सहायक",
    safeRoute: "सुरक्षित मार्ग और मैप",
    community: "समुदाय नेटवर्क",
    reportIncident: "घटना रिपोर्ट करें",
    education: "सुरक्षा शिक्षा और कानून",
    familySafety: "परिवार मोड",
    ruralSupport: "ग्रामीण सहायता",
    citySmart: "स्मार्ट सिटी सुरक्षा",
    quickActions: "त्वरित सुरक्षा टूल",
    sosAction: "तत्काल सहायता के लिए टैप करें",
    langName: "भाषा",
    chatPrompt: "आज मैं आपकी सुरक्षा में कैसे मदद कर सकता हूँ?",
    fakeCall: "फेक कॉल (Fake Call)",
    fakeCallDesc: "खतरे की स्थिति से निकलने के लिए फर्जी कॉल सिमुलेशन।",
    policeSiren: "पुलिस सायरन",
    policeSirenDesc: "आस-पास के लोगों को सतर्क करने के लिए तेज सायरन।",
    voiceSos: "वॉइस SOS",
    voiceSosDesc: "आवाज से ट्रिगर होने वाला SOS (जैसे 'Help', 'बचाओ')।",
    safetyTimer: "सुरक्षा टाइमर",
    safetyTimerDesc: "यात्रा के दौरान स्वचालित चेक-इन टाइमर।",
    policeFinder: "पुलिस स्टेशन खोजें",
    policeFinderDesc: "नाम, जिला या पिन कोड से नजदीकी थाना खोजें।",
    emergencyContacts: "SOS संपर्क सूची",
    emergencyContactsDesc: "आपात स्थिति में SMS भेजने के लिए विश्वसनीय संपर्क।",
    liveTrip: "लाइव ट्रिप शेयरिंग",
    liveTripDesc: "स्वजनों के साथ अपनी लाइव GPS लोकेशन साझा करें।",
    safetyHeatmap: "सुरक्षा हीटमैप",
    safetyHeatmapDesc: "सुरक्षित और संवेदनशील क्षेत्रों का नक्शा देखें।",
    helplines: "आपातकालीन हेल्पलाइन",
    features: "सभी फीचर्स और टूल्स",
    searchPolicePlaceholder: "थाना, जिला या पिन कोड दर्ज करें (जैसे 712601, 712413)...",
    noPoliceFound: "कोई पुलिस स्टेशन नहीं मिला।",
    navigate: "दिशा-निर्देश",
    call: "कॉल करें",
    pinCode: "पिन कोड",
    addContact: "संपर्क जोड़ें",
    noContacts: "अभी कोई संपर्क नहीं जोड़ा गया है।",
    startSharing: "शेयरिंग शुरू करें",
    stopSharing: "शेयरिंग बंद करें",
    startTimer: "टाइमर शुरू करें",
    cancelTimer: "टाइमर रद्द करें",
    startListening: "सुनना शुरू करें",
    stopListening: "सुनना बंद करें",
    joinNetwork: "नेटवर्क से जुड़ें",
    submitReport: "रिपोर्ट सबमिट करें",
    adminPortal: "एडमिन पोर्टल",
    policeController: "पुलिस स्टेशन कंट्रोलर (Police Controller)",
    policeControllerDesc: "लाइव पुलिस कंट्रोल रूम एवं आपातकालीन मॉनिटर।",
    activeAlerts: "सक्रिय आपातकालीन अलर्ट",
    dispatchUnit: "PCR वैन भेजें",
  },
  ta: { heroTitle: "உங்கள் பாதுகாப்பு, உங்கள் உரிமை", emergencyBtn: "அவசர SOS" },
  te: { heroTitle: "మీ భద్రత, మీ హక్కు", emergencyBtn: "అత్యవసర SOS" },
  kn: { heroTitle: "ನಿಮ್ಮ ಸುರಕ್ಷತೆ, ನಿಮ್ಮ ಹಕ್ಕು", emergencyBtn: "ತುರ್ತು SOS" },
  ml: { heroTitle: "നിങ്ങളുടെ സുരക്ഷ, നിങ്ങളുടെ അവകാശം", emergencyBtn: "അടിയന്തര SOS" },
  mr: { heroTitle: "तुमची सुरक्षा, तुमचा अधिकार", emergencyBtn: "तातडीची SOS" },
  gu: { heroTitle: "તમારી સુરક્ષા, તમારો અધિકાર", emergencyBtn: "કટોકટી SOS" },
  pa: { heroTitle: "ਤੁਹਾਡੀ ਸੁਰੱਖਿਆ, ਤੁਹਾਡਾ ਅਧਿਕਾਰ", emergencyBtn: "ਐਮਰਜੈਂਸੀ SOS" },
  as: { heroTitle: "আপোনাৰ সুৰক্ষা, আপোনাৰ অধিকাৰ", emergencyBtn: "জৰুৰীকালীন SOS" },
  or: { heroTitle: "ଆପଣଙ୍କ ସୁରକ୍ଷା, ଆପଣଙ୍କ ଅଧିକାର", emergencyBtn: "ଜରୁରୀକାଳୀନ SOS" },
  ur: { heroTitle: "آپ کی حفاظت، آپ کا حق", emergencyBtn: "ہنگامی SOS" },
  sa: { heroTitle: "भवत्याः सुरक्षा, भवत्याः अधिकारः", emergencyBtn: "आपातकालीन SOS" },
  kok: { heroTitle: "तुमची सुरक्षा, तुमचो अधिकार", emergencyBtn: "आणीबाणी SOS" },
  mni: { heroTitle: "নাকো চাফতি, নাকো রাইত", emergencyBtn: "এমারজেন্সী SOS" },
  brx: { heroTitle: "नोंथांनि रैखाथि, नोंथांनि मोनथाय", emergencyBtn: "गाहाय SOS" },
  ks: { heroTitle: "تُہنٛز حفاطت، تُہنٛز حق", emergencyBtn: "ایمرجنسی SOS" },
  doi: { heroTitle: "तुंदी सुरक्षा, तुंदा अधिकार", emergencyBtn: "आपातकालीन SOS" },
  mai: { heroTitle: "अहाँक सुरक्षा, अहाँक अधिकार", emergencyBtn: "आपातकालीन SOS" },
  ne: { heroTitle: "तपाइँको सुरक्षा, तपाइँको अधिकार", emergencyBtn: "आपतकालीन SOS" },
  sat: { heroTitle: "ᱟᱢᱟᱜ ᱥᱩᱨᱚᱠᱠᱷᱟ, ᱟᱢᱟᱜ ᱚᱭᱫᱟᱹᱨ", emergencyBtn: "ᱟᱸᱴ ᱚᱠᱛᱚ SOS" },
};
