import React, { useState, useEffect, useRef } from 'react';
import { useLanguage } from '../LanguageContext';
import { useEmergency } from '../EmergencyContext';
import { findNearestPoliceStation } from '../services/policeDatabase';
import { generateOfflineSmsPayload, sendOfflineSmsDirect } from '../services/offlineEmergencyService';
import { triggerHapticHoldTick } from '../services/silentPanicService';
import { 
  AlertCircle, 
  Volume2, 
  Flashlight, 
  PhoneCall, 
  Share2, 
  MessageSquare, 
  Wifi, 
  WifiOff, 
  Vibrate, 
  Mic, 
  ShieldAlert, 
  Radio, 
  Lock 
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

export default function SOSButton() {
  const { t, language } = useLanguage();
  const isBn = language === 'bn';
  const { 
    emergency, 
    startEmergency, 
    startSilentPanicEmergency, 
    stopEmergency, 
    contacts, 
    isSilentPanic, 
    vibrationActive, 
    toggleVibration,
    silentAudioSnippets,
    audioLevel 
  } = useEmergency();

  const [alarmActive, setAlarmActive] = useState(false);
  const [flashlightOn, setFlashlightOn] = useState(false);
  const [online, setOnline] = useState(true);

  // 3-second hold states
  const [isHolding, setIsHolding] = useState(false);
  const [holdProgress, setHoldProgress] = useState(0); // 0 to 100
  const [holdTip, setHoldTip] = useState<string | null>(null);

  const holdTimerRef = useRef<number | null>(null);
  const holdStartTimeRef = useRef<number>(0);
  const holdTickCountRef = useRef<number>(0);

  useEffect(() => {
    setOnline(navigator.onLine);
    const handleOnline = () => setOnline(true);
    const handleOffline = () => setOnline(false);
    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);
    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
    };
  }, []);

  const nearestPS = emergency.location 
    ? findNearestPoliceStation(emergency.location.lat, emergency.location.lng)
    : null;

  const getAlertText = () => {
    if (!emergency.isActive || !emergency.location) return '';
    const mapUrl = `https://www.google.com/maps?q=${emergency.location.lat},${emergency.location.lng}`;
    return `⚠ WOMEN SAFETY EMERGENCY ALERT ⚠

Name: Citizen (Nirbhaya Sathi)
Emergency Type: ${emergency.isSilentPanic ? 'SILENT PANIC (3s Hold)' : emergency.type}
Time: ${new Date(emergency.startTime!).toLocaleString()}
Location: Lat ${emergency.location.lat.toFixed(5)}, Lng ${emergency.location.lng.toFixed(5)}

Live Tracking Link: ${mapUrl}

Nearest Police Station: ${nearestPS?.name || 'Arambagh PS / West Bengal Police'}
PS Contact: ${nearestPS?.contact || '112'}

Generated by Nirbhaya Sathi Safe Guard.`;
  };

  useEffect(() => {
    if (emergency.isActive && contacts && contacts.length > 0) {
      const text = getAlertText();
      fetch('/api/notify-contacts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ contacts, message: text })
      }).then(res => res.json())
        .then(data => {
          if (data.success) {
            console.log(`Alert sent to ${data.deliveredCount} contacts`);
          }
        }).catch(err => console.error("Notification failed", err));
    }
  }, [emergency.isActive]);

  const handleShareAlert = () => {
    const text = getAlertText();
    if (navigator.share) {
      navigator.share({ text }).catch(console.error);
    } else {
      navigator.clipboard?.writeText(text);
      alert(isBn ? "জরুরি অ্যালার্ট মেসেজ ক্লিপবোর্ডে কপি হয়েছে!" : "Emergency Alert Copied to Clipboard!");
    }
  };

  const handleSendOfflineSMS = () => {
    const coords = emergency.location || { lat: 22.8824, lng: 87.7842 };
    const smsPayload = generateOfflineSmsPayload({
      lat: coords.lat,
      lng: coords.lng,
      userName: 'Citizen in Danger',
      emergencyType: emergency.type || 'RED DANGER',
      nearestPS: nearestPS?.name || 'Arambagh PS'
    });

    const phoneNumbers = contacts.length > 0 
      ? contacts.map(c => c.phone) 
      : ['112'];

    sendOfflineSmsDirect(phoneNumbers, smsPayload);
  };

  // --------------------------------------------------------------------------
  // 3-Second Hold Gesture Handling for Silent Panic Mode
  // --------------------------------------------------------------------------
  const startHoldGesture = (e: React.SyntheticEvent) => {
    // If emergency is already active, handle regular tap to stop
    if (emergency.isActive) return;

    setIsHolding(true);
    setHoldProgress(0);
    setHoldTip(null);
    holdStartTimeRef.current = Date.now();
    holdTickCountRef.current = 0;

    triggerHapticHoldTick();

    if (holdTimerRef.current !== null) {
      clearInterval(holdTimerRef.current);
    }

    holdTimerRef.current = window.setInterval(() => {
      const elapsed = Date.now() - holdStartTimeRef.current;
      const progress = Math.min(100, (elapsed / 3000) * 100);
      setHoldProgress(progress);

      // Tactile tick every second (at ~1000ms, ~2000ms)
      const currentTick = Math.floor(elapsed / 1000);
      if (currentTick > holdTickCountRef.current) {
        holdTickCountRef.current = currentTick;
        triggerHapticHoldTick();
      }

      // 3 SECONDS COMPLETED -> Trigger Silent Panic Mode!
      if (elapsed >= 3000) {
        if (holdTimerRef.current !== null) {
          clearInterval(holdTimerRef.current);
          holdTimerRef.current = null;
        }
        setIsHolding(false);
        setHoldProgress(100);
        startSilentPanicEmergency();
      }
    }, 25);
  };

  const cancelOrReleaseHoldGesture = () => {
    if (emergency.isActive) {
      stopEmergency();
      return;
    }

    if (!isHolding) return;

    const elapsed = Date.now() - holdStartTimeRef.current;
    if (holdTimerRef.current !== null) {
      clearInterval(holdTimerRef.current);
      holdTimerRef.current = null;
    }
    setIsHolding(false);
    setHoldProgress(0);

    // If hold was less than 350ms, treat as standard quick tap SOS
    if (elapsed < 350) {
      startEmergency('Danger', false);
    } else if (elapsed < 3000) {
      // Released between 350ms and 3000ms: prompt user about the 3-second silent panic feature
      setHoldTip(
        isBn 
          ? "নিঃশব্দ প্যানিক মোডের জন্য বোতামটি পুরো ৩ সেকেন্ড ধরে রাখুন।" 
          : "Hold for full 3 seconds to engage Silent Panic Mode."
      );
      setTimeout(() => setHoldTip(null), 3500);
    }
  };

  // SVG circular progress calculation (radius = 98)
  const radius = 98;
  const circumference = 2 * Math.PI * radius;
  const strokeDashoffset = circumference - (holdProgress / 100) * circumference;

  return (
    <div className="flex flex-col items-center gap-6 select-none">
      {/* Online / Offline Status Badge */}
      <div className="flex items-center gap-2">
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-white/90 shadow-sm border border-gray-200">
          {online ? (
            <>
              <span className="w-2 h-2 rounded-full bg-emerald-500 animate-ping" />
              <Wifi className="w-3.5 h-3.5 text-emerald-600" />
              <span className="text-emerald-700">{isBn ? 'অনলাইন মোড (Live Sync)' : 'Online Live Mode'}</span>
            </>
          ) : (
            <>
              <span className="w-2 h-2 rounded-full bg-amber-500" />
              <WifiOff className="w-3.5 h-3.5 text-amber-600" />
              <span className="text-amber-700">{isBn ? 'অফলাইন মোড (SMS ও জিপিএস সচল)' : 'Offline Mode (SMS/GPS Active)'}</span>
            </>
          )}
        </div>

        {/* Silent Panic / Vibration Active Badge */}
        {emergency.isActive && emergency.isSilentPanic && (
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-black bg-slate-900 text-white shadow-sm border border-red-500/50 animate-pulse">
            <Vibrate className="w-3.5 h-3.5 text-red-400 animate-bounce" />
            <span>{isBn ? 'নিঃশব্দ প্যানিক সক্রিয় (Haptic + Audio)' : 'Silent Panic Active'}</span>
          </div>
        )}
      </div>

      {/* Main SOS Button with Circular 3-Second Hold Ring */}
      <div className="relative flex items-center justify-center">
        {/* Circular Progress Ring for 3-Second Hold */}
        <svg 
          className="absolute -inset-4 w-[13.5rem] h-[13.5rem] -rotate-90 pointer-events-none z-20"
          viewBox="0 0 220 220"
        >
          {/* Background guide track */}
          <circle
            cx="110"
            cy="110"
            r={radius}
            fill="none"
            stroke="currentColor"
            className={`text-slate-200 ${isHolding ? 'opacity-100' : 'opacity-0'} transition-opacity`}
            strokeWidth="8"
          />
          {/* Progress fill */}
          <circle
            cx="110"
            cy="110"
            r={radius}
            fill="none"
            stroke={isHolding ? "#dc2626" : "transparent"}
            strokeWidth="9"
            strokeDasharray={circumference}
            strokeDashoffset={strokeDashoffset}
            strokeLinecap="round"
            className="transition-all duration-75"
          />
        </svg>

        <motion.button
          onPointerDown={startHoldGesture}
          onPointerUp={cancelOrReleaseHoldGesture}
          onPointerLeave={cancelOrReleaseHoldGesture}
          onContextMenu={(e) => e.preventDefault()}
          whileHover={{ scale: 1.04 }}
          whileTap={{ scale: 0.94 }}
          className={`relative z-10 w-48 h-48 rounded-full flex flex-col items-center justify-center shadow-2xl transition-all duration-300 cursor-pointer touch-none ${
            emergency.isActive 
              ? emergency.isSilentPanic
                ? 'bg-slate-900 border-4 border-red-500 scale-105 shadow-red-900/50'
                : 'bg-red-600 scale-110 shadow-red-500/50' 
              : isHolding
              ? 'bg-red-700 shadow-red-700/60 scale-105'
              : 'bg-gradient-to-tr from-red-600 to-rose-500 hover:from-red-700 hover:to-rose-600 shadow-red-500/40'
          }`}
        >
          <div className="flex flex-col items-center text-white px-2 text-center">
            {emergency.isActive ? (
              emergency.isSilentPanic ? (
                <>
                  <Mic className="w-12 h-12 mb-1 text-red-400 animate-pulse" />
                  <span className="font-black text-lg tracking-wider text-white">SILENT PANIC</span>
                  <span className="text-[10px] font-bold text-red-300 uppercase tracking-widest flex items-center gap-1">
                    <span className="w-1.5 h-1.5 rounded-full bg-red-400 animate-ping" />
                    STREAMING
                  </span>
                </>
              ) : (
                <>
                  <AlertCircle className="w-14 h-14 mb-1 animate-pulse" />
                  <span className="font-black text-2xl tracking-wider">{isBn ? 'বন্ধ করুন' : 'STOP'}</span>
                </>
              )
            ) : isHolding ? (
              <>
                <Vibrate className="w-10 h-10 mb-1 animate-bounce text-amber-300" />
                <span className="font-black text-xs tracking-wider text-amber-200">
                  {Math.ceil((3000 - (holdProgress / 100) * 3000) / 1000)}s
                </span>
                <span className="font-black text-xs uppercase tracking-tight text-white mt-0.5">
                  HOLD FOR SILENT
                </span>
              </>
            ) : (
              <>
                <AlertCircle className="w-14 h-14 mb-1" />
                <span className="font-black text-3xl tracking-wider">SOS</span>
                <span className="text-[10px] text-red-100 font-bold opacity-90 mt-0.5">
                  {isBn ? '৩ সেকেন্ড ধরে রাখুন' : 'HOLD 3s: SILENT'}
                </span>
              </>
            )}
          </div>
          
          {emergency.isActive && (
            <motion.div 
              initial={{ scale: 0.8, opacity: 0 }}
              animate={{ scale: 1.5, opacity: 0 }}
              transition={{ repeat: Infinity, duration: 1.5 }}
              className={`absolute inset-0 rounded-full -z-10 ${
                emergency.isSilentPanic ? 'bg-slate-700' : 'bg-red-400'
              }`}
            />
          )}
        </motion.button>
      </div>

      {/* Hold Hint / Instruction Tooltip */}
      {holdTip && (
        <motion.div
          initial={{ opacity: 0, y: -5 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0 }}
          className="bg-slate-900 text-white text-xs font-bold px-4 py-2 rounded-2xl shadow-xl border border-red-500/40 flex items-center gap-2"
        >
          <Vibrate className="w-4 h-4 text-amber-400 animate-pulse" />
          <span>{holdTip}</span>
        </motion.div>
      )}

      {/* Direct Trigger button for Silent Panic Mode (Instant access alternative) */}
      {!emergency.isActive && (
        <div className="flex flex-col sm:flex-row items-center gap-2.5">
          <button
            onClick={() => startSilentPanicEmergency()}
            className="group px-5 py-2.5 rounded-2xl bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs flex items-center gap-2.5 shadow-md border border-slate-700 transition-all cursor-pointer hover:border-red-500/50"
          >
            <div className="w-6 h-6 rounded-lg bg-red-600/30 text-red-400 flex items-center justify-center group-hover:bg-red-600 group-hover:text-white transition-colors">
              <Vibrate className="w-3.5 h-3.5" />
            </div>
            <div className="text-left">
              <span className="block text-white font-extrabold">
                {isBn ? 'নিঃশব্দ প্যানিক মোড' : 'Silent Panic Mode'}
              </span>
              <span className="block text-[10px] text-slate-400 font-normal">
                {isBn ? '৩ সেকেন্ড প্রেস বা সরাসরি ট্যাপ করুন (Haptic + Audio)' : '3s Hold or Tap • Device Vibration & Audio Stream'}
              </span>
            </div>
          </button>
        </div>
      )}

      {/* Active Emergency Action Grid */}
      <AnimatePresence>
        {emergency.isActive && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 20 }}
            className="grid grid-cols-2 sm:grid-cols-3 gap-3 w-full max-w-md"
          >
            {/* Haptic Vibration Control Button */}
            <ActionButton 
              icon={<Vibrate className={vibrationActive ? 'animate-bounce text-red-400' : ''} />} 
              label={vibrationActive ? (isBn ? "ভাইব্রেশন চালু" : "Vibrating") : (isBn ? "ভাইব্রেশন বন্ধ" : "Vibration Off")} 
              active={vibrationActive} 
              onClick={toggleVibration} 
              color="bg-slate-900 border border-red-500/50"
            />
            <ActionButton 
              icon={<Volume2 className={alarmActive ? 'animate-bounce' : ''} />} 
              label={isBn ? "সাইরেন" : "Siren"} 
              active={alarmActive} 
              onClick={() => setAlarmActive(!alarmActive)} 
              color="bg-orange-500"
            />
            <ActionButton 
              icon={<Flashlight />} 
              label={isBn ? "ফ্ল্যাশ" : "Flash"} 
              active={flashlightOn} 
              onClick={() => setFlashlightOn(!flashlightOn)} 
              color="bg-yellow-500"
            />
            <ActionButton 
              icon={<MessageSquare />} 
              label={isBn ? "অফলাইন SMS" : "Offline SMS"} 
              active={true} 
              onClick={handleSendOfflineSMS} 
              color="bg-purple-600"
            />
            <ActionButton 
              icon={<Share2 />} 
              label={isBn ? "শেয়ার লিংক" : "Share Alert"} 
              active={true} 
              onClick={handleShareAlert} 
              color="bg-blue-600"
            />
            <ActionButton 
              icon={<PhoneCall />} 
              label={nearestPS ? (isBn ? `কল থানা` : `Call ${nearestPS.name.split(' ')[0]}`) : "Call 112"} 
              active={false} 
              onClick={() => window.open(`tel:${nearestPS?.contact || '112'}`)} 
              color="bg-emerald-600"
            />
          </motion.div>
        )}
      </AnimatePresence>

      <div className="text-center space-y-1">
        <p className="text-gray-600 text-sm font-bold">
          {emergency.isActive 
            ? emergency.isSilentPanic
              ? (isBn ? '🤫 নিঃশব্দ প্যানিক মোড: ডিভাইস ভাইব্রেশন এবং রিয়েল-টাইম অডিও স্ট্রিম পুলিশে প্রেরিত হচ্ছে' : '🤫 SILENT PANIC ACTIVE: Tactile Vibration & Live Audio Stream Auto-Uploading')
              : (isBn ? '🚨 পুলিশ ও পরিবারে সতর্কবার্তা পাঠানো হয়েছে' : 'POLICE & RESCUE ALERT ACTIVATED')
            : t('sosAction') || 'Tap for SOS • Hold 3 seconds for Silent Panic'}
        </p>
        {emergency.isActive && nearestPS && (
          <p className="text-red-600 text-xs font-black animate-pulse">
            {isBn ? `নিকটবর্তী থানা: ${nearestPS.name} (${nearestPS.contact})` : `Nearest Police Station: ${nearestPS.name}`}
          </p>
        )}
      </div>
    </div>
  );
}

function ActionButton({ icon, label, active, onClick, color }: any) {
  return (
    <button
      onClick={onClick}
      className={`flex items-center gap-3 p-4 rounded-2xl transition-all cursor-pointer ${
        active 
          ? color + ' text-white shadow-lg' 
          : 'bg-white text-gray-600 hover:bg-gray-100 border border-gray-100'
      }`}
    >
      <div className={active ? 'text-white' : 'text-gray-500'}>
        {React.cloneElement(icon, { size: 20 })}
      </div>
      <span className="font-bold text-xs uppercase tracking-wider">{label}</span>
    </button>
  );
}
